#include "element.hpp"

using namespace element;

std::string element::info::list[] = {"H",
                                     "He",
                                     "Li",
                                     "Be",
                                     "B",
                                     "C",
                                     "N",
                                     "O",
                                     "F",
                                     "Ne",
                                     "Na",
                                     "Mg",
                                     "Al",
                                     "Si",
                                     "P",
                                     "S",
                                     "Cl",
                                     "Ar",
                                     "K",
                                     "Ca",
                                     "Sc",
                                     "Ti",
                                     "V",
                                     "Cr",
                                     "Mn",
                                     "Fe",
                                     "Co",
                                     "Ni",
                                     "Cu",
                                     "Zn",
                                     "Ga",
                                     "Ge",
                                     "As",
                                     "Se",
                                     "Br",
                                     "Kr",
                                     "Rb",
                                     "Sr",
                                     "Y",
                                     "Zr",
                                     "Nb",
                                     "Mo",
                                     "Tc",
                                     "Ru",
                                     "Rh",
                                     "Pd",
                                     "Ag",
                                     "Cd",
                                     "In",
                                     "Sn",
                                     "Sb",
                                     "Te",
                                     "I",
                                     "Xe",
                                     "Cs",
                                     "Ba",
                                     "La",
                                     "Ce",
                                     "Pr",
                                     "Nd",
                                     "Pm",
                                     "Sm",
                                     "Eu",
                                     "Gd",
                                     "Tb",
                                     "Dy",
                                     "Ho",
                                     "Er",
                                     "Tm",
                                     "Yb",
                                     "Lu",
                                     "Hf",
                                     "Ta",
                                     "W",
                                     "Re",
                                     "Os",
                                     "Ir",
                                     "Pt",
                                     "Au",
                                     "Hg",
                                     "Tl",
                                     "Pb",
                                     "Bi",
                                     "Po",
                                     "At",
                                     "Rn",
                                     "Fr",
                                     "Ra",
                                     "Ac",
                                     "Th",
                                     "Pa",
                                     "U",
                                     "Np",
                                     "Pu",
                                     "Am",
                                     "Cm",
                                     "Bk",
                                     "Cf",
                                     "Es",
                                     "Fm",
                                     "Md",
                                     "No",
                                     "Lr",
                                     "Rf",
                                     "Db",
                                     "Sg",
                                     "Bh",
                                     "Hs",
                                     "Mt",
                                     "Ds",
                                     "Rg",
                                     "Cn",
                                     "Nh",
                                     "Fl",
                                     "Mc",
                                     "Lv",
                                     "Ts",
                                     "Og"};
/* "Ung", Outdated element signs == DEPRECATED
   "Unp",
   "Unh",
   "Uns",
   "Uno",
   "Une",
   "Uun",
   "Uuu",
   "Uub"};
*/

std::string element::info::list_long[] = { "Hydrogen",
                                           "Helium",
                                           "Lithium",
                                           "Beryllium",
                                           "Boron",
                                           "Carbon",
                                           "Nitrogen",
                                           "Oxygen",
                                           "Fluorine",
                                           "Neon",
                                           "Sodium",
                                           "Magnesium",
                                           "Aluminum",
                                           "Silicon",
                                           "Phosphorus",
                                           "Sulfur",
                                           "Chlorine",
                                           "Argon",
                                           "Potassium",
                                           "Calcium",
                                           "Scandium",
                                           "Titanium",
                                           "Vanadium",
                                           "Chromium",
                                           "Manganese",
                                           "Iron",
                                           "Cobalt",
                                           "Nickel",
                                           "Copper",
                                           "Zinc",
                                           "Gallium",
                                           "Germanium",
                                           "Arsenic",
                                           "Selenium",
                                           "Bromine",
                                           "Krypton",
                                           "Rubidium",
                                           "Strontium",
                                           "Yttrium",
                                           "Zirconium",
                                           "Niobium",
                                           "Molybdenum",
                                           "Technetium",
                                           "Ruthenium",
                                           "Rhodium",
                                           "Palladium",
                                           "Silver",
                                           "Cadmium",
                                           "Indium",
                                           "Tin",
                                           "Antimony",
                                           "Tellurium",
                                           "Iodine",
                                           "Xenon",
                                           "Cesium",
                                           "Barium",
                                           "Lanthanum",
                                           "Cerium",
                                           "Praseodymium",
                                           "Neodymium",
                                           "Promethium",
                                           "Samarium",
                                           "Europium",
                                           "Gadolinium",
                                           "Terbium",
                                           "Dysprosium",
                                           "Holmium",
                                           "Erbium",
                                           "Thulium",
                                           "Ytterbium",
                                           "Lutetium",
                                           "Hafnium",
                                           "Tantalum",
                                           "Tungsten",
                                           "Rhenium",
                                           "Osmium",
                                           "Iridium",
                                           "Platinum",
                                           "Gold",
                                           "Mercury",
                                           "Thallium",
                                           "Lead",
                                           "Bismuth",
                                           "Polonium",
                                           "Astatine",
                                           "Radon",
                                           "Francium",
                                           "Radium",
                                           "Actinium",
                                           "Thorium",
                                           "Protactinium",
                                           "Uranium",
                                           "Neptunium",
                                           "Plutonium",
                                           "Americium",
                                           "Curium",
                                           "Berkelium",
                                           "Californium",
                                           "Einsteinium",
                                           "Fermium",
                                           "Mendelevium",
                                           "Nobelium",
                                           "Lawrencium",
                                           "Rutherfordium",
                                           "Dubnium",
                                           "Seaborgium",
                                           "Bohrium",
                                           "Hassium",
                                           "Meitnerium",
                                           "Darmstadtium",
                                           "Roentgenium",
                                           "Copernicium",
                                           "Nihonium",
                                           "Flerovium",
                                           "Moscovium",
                                           "Livermorium",
                                           "Tennessine",
                                           "Oganesson",
};




std::string element::info::states[] = {"Solid", "Gas", "Liquid", "Unknown"};

int element::info::n_of_elements = sizeof(element::info::list)/sizeof(element::info::list[0]);

bool flags::FULLNAME_M = false;
bool flags::BYNUM_M = false;
bool flags::CASE = true;
bool flags::COLOR = true;
bool flags::NAME_ONLY = false;
bool flags::NAME = true;
bool flags::SIGN = true;
bool flags::MASS = false;
bool flags::ATOMIC = true;
bool flags::POS = false;
bool flags::STP_STATE = false;
bool flags::RADS = false;


struct option element::info::long_opts[] = {
    {"all",            no_argument,   NULL, 'A' },
    {"rad",            no_argument,   NULL, 'r' },
    {"mass",           no_argument,   NULL, 'm' },
    {"name-only",      no_argument,   NULL, 'n' },
    {"stp-state",      no_argument,   NULL, 's' },
    {"position",       no_argument,   NULL, 'p' },
    {"help",           no_argument,   NULL, 'h' },
    {"dump-elements",  no_argument,   NULL, 'd' },
    {"no-color",       no_argument,   NULL, 'c' },
    {"insensitive",    no_argument,   NULL, 'i' },
    {"full-name",      no_argument,   NULL, 'f' },
    {"by-number",      no_argument,   NULL, 'b' },
    {NULL,             0,             NULL,  0  },
};
